# Rendered ipynb files and kernel metadata json files for this config will be saved at notebooks/<track>/<tag>/
tag: prod
public: true
# If true, then exercise kernels synced to kaggle will have internet enabled and will begin
# with a cell that pip installs the current learntools branch. (Useful for testing 
# notebooks on Kernels without requiring image docker deploy for every learntools change)
development: false
# By itself, this flag does nothing. But it can be useful to have 'testing' cells in exercise
# notebooks (testing the checking code on various correct and incorrect solutions) whose 
# inclusion in the rendered notebook is conditioned on this flag (using a macro like #%%RM_IF(PROD)%%
# where "prod" is the opposite of "testing")
testing: false
# A string to append to titles and slugs of kernels generated under this config (so that the generated
# kernels are pushed to a separate destination from the default config). If testing is true, suffix 
# defaults to 'testing'. (Spaces and special characters are allowed and will be munged appropriately when appending to slug)
#suffix: foo
# Author username usually gets set in track_meta.py. The following optional key will overwrite
# the author for kernels generated under this particular config. (Example use case: author A
# is working on notebooks originally authored by author B. The default 'production' notebooks
# should keep their original slugs under author B's namespace. But if author A wants to push
# new testing versions of the notebook, they can set author: author_A in testing.yaml to generate
# new versions of the kernels under their own username.
author: dansbecker
